#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env"

DEFAULT_APP_NAME="vlm-server"
DEFAULT_APP_ENV="prod"
DEFAULT_GPU_IDS="5,6"
DEFAULT_HOST="127.0.0.1"
DEFAULT_PORT="8972"
DEFAULT_LOG_LEVEL="info"
DEFAULT_MODEL_NAME="Qwen3.5-27B"
DEFAULT_MODEL_PATH="/home/user/g00806422/data/weight/Qwen3.5-27B"
DEFAULT_INFERENCE_BACKEND="vllm"
DEFAULT_TENSOR_PARALLEL_SIZE="2"
DEFAULT_SKIP_MODEL_LOAD="false"
DEFAULT_MAX_INPUT_IMAGES="4"
DEFAULT_MAX_IMAGE_BYTES="20971520"
DEFAULT_DEFAULT_MAX_TOKENS="512"
DEFAULT_MAX_OUTPUT_TOKENS_LIMIT="10240"
DEFAULT_DEFAULT_TEMPERATURE="0.1"
DEFAULT_INFERENCE_CONCURRENCY="1"
DEFAULT_REQUEST_TIMEOUT_SECONDS="120"
DEFAULT_ALLOW_FILE_PATH_INPUT="true"
DEFAULT_ALLOW_BASE64_INPUT="true"

if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
  set +a
fi

export PYTHONPATH="${ROOT_DIR}:${PYTHONPATH:-}"
export APP_NAME="${APP_NAME:-${DEFAULT_APP_NAME}}"
export APP_ENV="${APP_ENV:-${DEFAULT_APP_ENV}}"
export GPU_IDS="${GPU_IDS:-${DEFAULT_GPU_IDS}}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-${GPU_IDS}}"
export HOST="${HOST:-${DEFAULT_HOST}}"
export PORT="${PORT:-${DEFAULT_PORT}}"
export LOG_LEVEL="${LOG_LEVEL:-${DEFAULT_LOG_LEVEL}}"
export MODEL_NAME="${MODEL_NAME:-${DEFAULT_MODEL_NAME}}"
export MODEL_PATH="${MODEL_PATH:-${DEFAULT_MODEL_PATH}}"
export INFERENCE_BACKEND="${INFERENCE_BACKEND:-${DEFAULT_INFERENCE_BACKEND}}"
export TENSOR_PARALLEL_SIZE="${TENSOR_PARALLEL_SIZE:-${DEFAULT_TENSOR_PARALLEL_SIZE}}"
export SKIP_MODEL_LOAD="${SKIP_MODEL_LOAD:-${DEFAULT_SKIP_MODEL_LOAD}}"
export MAX_INPUT_IMAGES="${MAX_INPUT_IMAGES:-${DEFAULT_MAX_INPUT_IMAGES}}"
export MAX_IMAGE_BYTES="${MAX_IMAGE_BYTES:-${DEFAULT_MAX_IMAGE_BYTES}}"
export DEFAULT_MAX_TOKENS="${DEFAULT_MAX_TOKENS:-${DEFAULT_DEFAULT_MAX_TOKENS}}"
export MAX_OUTPUT_TOKENS_LIMIT="${MAX_OUTPUT_TOKENS_LIMIT:-${DEFAULT_MAX_OUTPUT_TOKENS_LIMIT}}"
export DEFAULT_TEMPERATURE="${DEFAULT_TEMPERATURE:-${DEFAULT_DEFAULT_TEMPERATURE}}"
export INFERENCE_CONCURRENCY="${INFERENCE_CONCURRENCY:-${DEFAULT_INFERENCE_CONCURRENCY}}"
export REQUEST_TIMEOUT_SECONDS="${REQUEST_TIMEOUT_SECONDS:-${DEFAULT_REQUEST_TIMEOUT_SECONDS}}"
export ALLOW_FILE_PATH_INPUT="${ALLOW_FILE_PATH_INPUT:-${DEFAULT_ALLOW_FILE_PATH_INPUT}}"
export ALLOW_BASE64_INPUT="${ALLOW_BASE64_INPUT:-${DEFAULT_ALLOW_BASE64_INPUT}}"

echo "[run_server] root_dir=${ROOT_DIR}"
echo "[run_server] cuda_visible_devices=${CUDA_VISIBLE_DEVICES}"
echo "[run_server] tensor_parallel_size=${TENSOR_PARALLEL_SIZE}"
echo "[run_server] host=${HOST} port=${PORT}"
echo "[run_server] model=${MODEL_NAME}"
echo "[run_server] model_path=${MODEL_PATH}"
echo "[run_server] backend=${INFERENCE_BACKEND}"
echo "[run_server] skip_model_load=${SKIP_MODEL_LOAD}"
echo "[run_server] max_output_tokens_limit=${MAX_OUTPUT_TOKENS_LIMIT}"

exec python -m uvicorn app.main:app --host "${HOST}" --port "${PORT}"
